### ISSUE TITLE
Está bien, pero quizá no hag falta

### ISSUE THREAD

**Issue by itacademyReact** [MireiaBS/Tienda-Online-JS#1]
Podrías haber nombrado productoId el parámetro de entrada de la función, quedando:

function addToCart(productoId) {
...
}

https://github.com/MireiaBS/Online-Store/blob/b09b9d49d5717db9288e8d83b9133af99a77efd9/js/shop.js#L48

**Comment by MireiaBS** [comment]
Vale, queda redundante entiendo.  Mersi por los tips
